# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_struc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13message_struc.proto\"O\n\x06Rating\x12\x12\n\nreviewerID\x18\x01 \x01(\t\x12\x0c\n\x04\x61sin\x18\x02 \x01(\t\x12\x0f\n\x07overall\x18\x03 \x01(\x05\x12\x12\n\nreviewText\x18\x04 \x01(\t\"B\n\rAverageRating\x12\x0c\n\x04\x61sin\x18\x01 \x01(\t\x12\x14\n\x0cmean_overall\x18\x02 \x01(\x02\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"8\n\x0e\x41verageRatings\x12&\n\x0e\x61verage_rating\x18\x01 \x03(\x0b\x32\x0e.AverageRatingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_struc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RATING._serialized_start=23
  _RATING._serialized_end=102
  _AVERAGERATING._serialized_start=104
  _AVERAGERATING._serialized_end=170
  _AVERAGERATINGS._serialized_start=172
  _AVERAGERATINGS._serialized_end=228
# @@protoc_insertion_point(module_scope)
